Text Classificaition is a supervised ML Based task where we to assign a given input into classes and the data point is textual in nature.It can be word,sentence or any phrase.
In this code we will be learning ML approach for doing Text Classification
Focus will be on ML Model Building Using Different Text Classification Techniques
 -  Bag of Words
 -  N-gram
 -  TF-IDF
 -  Word2Vec
 
ML Model Used will be 
 -  Naive Bayes
 -  Random Forest Classifier
 
Dataset used : IMDB 50K Movies Review Dataset from Kaggle below is the link:

https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews/data

In [1]:
# Importing the dependencies

import numpy as np
import pandas as pd

In [2]:
# Coverting into Dataframe

temp_df = pd.read_csv('IMDBDataset.csv')

In [3]:
# Since the approach here it to show how the model building work so we will be working with less data 
# So we select first 10k rows from the dataset for lesser computation time.

df = temp_df[:10000] # Using only 10K rows

df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
# Checking the review 1
df.review[1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well d

In [5]:
# Basic Data-preprocessing 

df.sentiment.value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [6]:
# Checking Null Values

df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [7]:
# Checking Duplicate values

df.duplicated().sum()

17

In [8]:
# Removing Duplicate columns

df.drop_duplicates(inplace=True)

/var/folders/wz/2jqdvyrx06bb89dg_4hb4hv80000gn/T/ipykernel_69568/3757011987.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)


In [9]:
#Checking the result post removing the duplicate entries
df.duplicated().sum()

0

In [10]:
# Basic Text Preprocessing > We will implement basis text preprocessing to make text clear which include
# Remove tags
# Lowercasing
# remove stopwords

In [11]:
# removing Html Tags
import re

def remove_tags(t):
    cleaned_txt = re.sub(re.compile('<.*?>'), "", t)
    return cleaned_txt

In [12]:
df.review = df.review.apply(remove_tags)

df.head()

/var/folders/wz/2jqdvyrx06bb89dg_4hb4hv80000gn/T/ipykernel_69568/260009993.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.review = df.review.apply(remove_tags)


review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. The filming tec...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [13]:
# Applying Lowercasing

df.review = df.review.apply(lambda x: x.lower())

/var/folders/wz/2jqdvyrx06bb89dg_4hb4hv80000gn/T/ipykernel_69568/753081429.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.review = df.review.apply(lambda x: x.lower())


In [14]:
df

review sentiment
0     one of the other reviewers has mentioned that ...  positive
1     a wonderful little production. the filming tec...  positive
2     i thought this was a wonderful way to spend ti...  positive
3     basically there's a family where a little boy ...  negative
4     petter mattei's "love in the time of money" is...  positive
...                                                 ...       ...
9995  fun, entertaining movie about wwii german spy ...  positive
9996  give me a break. how can anyone say that this ...  negative
9997  this movie is a bad movie. but after watching ...  negative
9998  this is a movie that was probably made to ente...  negative
9999  smashing film about film-making. shows the int...  positive

[9983 rows x 2 columns]

In [15]:
# removing stop words

from nltk.corpus import stopwords

sw_list = stopwords.words('english')

df.review = df.review.apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))
    

/var/folders/wz/2jqdvyrx06bb89dg_4hb4hv80000gn/T/ipykernel_69568/3279720599.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.review = df.review.apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))


In [16]:
# Checking final output after text-preprocessing
df.review

0       one reviewers mentioned watching 1 oz episode ...
1       wonderful little production. filming technique...
2       thought wonderful way spend time hot summer we...
3       basically there's family little boy (jake) thi...
4       petter mattei's "love time money" visually stu...
                              ...                        
9995    fun, entertaining movie wwii german spy (julie...
9996    give break. anyone say "good hockey movie"? kn...
9997    movie bad movie. watching endless series bad h...
9998    movie probably made entertain middle school, e...
9999    smashing film film-making. shows intense stran...
Name: review, Length: 9983, dtype: object

In [17]:
# Splitting the data into predictor and target variable
x = df.iloc[:,0:1]
y = df.sentiment

In [18]:
x

review
0     one reviewers mentioned watching 1 oz episode ...
1     wonderful little production. filming technique...
2     thought wonderful way spend time hot summer we...
3     basically there's family little boy (jake) thi...
4     petter mattei's "love time money" visually stu...
...                                                 ...
9995  fun, entertaining movie wwii german spy (julie...
9996  give break. anyone say "good hockey movie"? kn...
9997  movie bad movie. watching endless series bad h...
9998  movie probably made entertain middle school, e...
9999  smashing film film-making. shows intense stran...

[9983 rows x 1 columns]

In [19]:
y

0       positive
1       positive
2       positive
3       negative
4       positive
          ...   
9995    positive
9996    negative
9997    negative
9998    negative
9999    positive
Name: sentiment, Length: 9983, dtype: object

In [20]:
# Applying label encode on Y

from sklearn.preprocessing import LabelEncoder

lb = LabelEncoder()

y = lb.fit_transform(y)

In [21]:
# Checking the result
y

array([1, 1, 1, ..., 0, 0, 1])

In [22]:
# Splitting the data into train and test

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, train_size=0.8, random_state=1)

In [23]:
x_train.shape

(7986, 1)

### Applying Bag of Words

In [24]:
# Apply BOW

from sklearn.feature_extraction.text import CountVectorizer

# Intializing the object

cv = CountVectorizer()

In [25]:
# Coverting x_train, x_test into vectors using BOW technique

x_train_bow = cv.fit_transform(x_train.review).toarray()
x_test_bow = cv.transform(x_test.review).toarray()

In [26]:
#Checking the result

x_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [27]:
#checking the shape

x_train_bow.shape

(7986, 48282)

In [28]:
# Building ML Model 

# Naive Bayes

from sklearn.naive_bayes import GaussianNB

gb = GaussianNB()

gb.fit(x_train_bow,y_train)

GaussianNB()

In [29]:
#prediction

y_pred = gb.predict(x_test_bow)

In [30]:
# Model Evalualtion

from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.6324486730095142

Poor Accuracy, We can do hypertunning to take more data 

In [31]:
confusion_matrix(y_test,y_pred)

array([[717, 235],
       [499, 546]])

Lot of Errors in confusion Matrix

In [32]:
# Random Forest Classifier

from sklearn.ensemble import RandomForestClassifier

#Initalizing the object

rf = RandomForestClassifier()

# Training the model
rf.fit(x_train_bow,y_train)

#prediction
y_pred1 = rf.predict(x_test_bow)

#evaluation
accuracy_score(y_test, y_pred1)

0.8477716574862293

Better Results than Naive Bayes

In [33]:
# Random Forest Classifier by Reducing the corpus size

#Creating a new object and taking max 3000 word in vocabulary
cv = CountVectorizer(max_features=3000) 

# Applying Vectorization on x_train and x_test
x_train_bow = cv.fit_transform(x_train.review).toarray()
x_test_bow = cv.transform(x_test.review).toarray()

#Creating Model Object
rf = RandomForestClassifier()

# training the model
rf.fit(x_train_bow,y_train)

#prediction
y_pred2 = rf.predict(x_test_bow)

#evaluation
accuracy_score(y_test, y_pred2)

0.8362543815723585

No Much improvement in Accuracy

## Using N-Gram

In [34]:
# Applying N-gram  

# creating Bi-gram object with Max vocab of 3000

cv = CountVectorizer(ngram_range=(2,2), max_features=5000)

# Vectorizing x_train and x_test
x_train_bow = cv.fit_transform(x_train.review).toarray()
x_test_bow = cv.transform(x_test.review).toarray()

#creating model object
rf = RandomForestClassifier()

#training the model
rf.fit(x_train_bow,y_train)

#prediction
y_pred3 = rf.predict(x_test_bow)

#evaluation 
accuracy_score(y_test, y_pred3)

0.7506259389083625

Not a high accuracy due to less vocab and data, fine tunning we can be used to increase the accuracy.

## Using TF-IDF

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer

#creating tfidf obejct
tfidf = TfidfVectorizer()

In [36]:
#applying TF-IDF vectorizaiton on x_train and x_test

x_train_tfidf = tfidf.fit_transform(x_train.review).toarray()
x_test_tfidf = tfidf.transform(x_test.review).toarray()

In [37]:
# Model Building

#Creating Model Object
rf = RandomForestClassifier()

#training the model
rf.fit(x_train_tfidf,y_train)

#prediciton
y_pred3 = rf.predict(x_test_tfidf)

#evaluation
accuracy_score(y_test, y_pred3)

0.85578367551327

Accuracy has been improved not much. However using fine tunning with model object and tfidf object we can increase the accuracy

## Using Word2Vec

In [38]:
# In using Word2Vec we need to ensure that we use the complete data to get the better results

#Importing the dependencies
import gensim
from gensim.utils import simple_preprocess
from nltk import sent_tokenize

In [39]:
# creating new df

temp_df = pd.read_csv('IMDBDataset.csv')
df = temp_df[:10000]

In [40]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [41]:
# checking null values

df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [42]:
# checking duplicates

df.duplicated().sum()

17

In [43]:
# Dropping for duplicates

df.drop_duplicates(inplace=True)

/var/folders/wz/2jqdvyrx06bb89dg_4hb4hv80000gn/T/ipykernel_69568/720423787.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)


In [44]:
# Basic Text Preprocessing 


# Removing html_tags
df.review = df.review.apply(remove_tags)

# Lowercasing

df.review = df.review.apply(lambda x: x.lower())

# removing stopwords

df.review = df.review.apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

df.review

/var/folders/wz/2jqdvyrx06bb89dg_4hb4hv80000gn/T/ipykernel_69568/2297666349.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.review = df.review.apply(remove_tags)
/var/folders/wz/2jqdvyrx06bb89dg_4hb4hv80000gn/T/ipykernel_69568/2297666349.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.review = df.review.apply(lambda x: x.lower())
/var/folders/wz/2jqdvyrx06bb89dg_4hb4hv80000gn/T/ipykernel_69568/2297666349.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a Da

0       one reviewers mentioned watching 1 oz episode ...
1       wonderful little production. filming technique...
2       thought wonderful way spend time hot summer we...
3       basically there's family little boy (jake) thi...
4       petter mattei's "love time money" visually stu...
                              ...                        
9995    fun, entertaining movie wwii german spy (julie...
9996    give break. anyone say "good hockey movie"? kn...
9997    movie bad movie. watching endless series bad h...
9998    movie probably made entertain middle school, e...
9999    smashing film film-making. shows intense stran...
Name: review, Length: 9983, dtype: object

In [45]:
# Applying Word2Vec or creating the corpus

story = []

for doc in df.review:
    raw_sent = sent_tokenize(doc)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [46]:
# Building Word2Vec Model

model = gensim.models.Word2Vec(window=10,min_count=2)

# Building Vocabulary

model.build_vocab(story)

# Training the model

model.train(story, total_examples=model.corpus_count , epochs=model.epochs)

(5875673, 6212140)

In [47]:
# Checking the length

len(model.wv.index_to_key)

31845

In [48]:
# Now we have vectors for words in corpus and now we need to create the vector for review columns

# Creating vectors for reviews > In this approach we basically compare each word in review with the vocabulary words
# and then replace them with the corresponding vector
# Once we get the corresponding vector for each word in a particular review then we will apply Average Word2Vec
# Technique to calculate the vector for the entire review by simply doing Vector Addition and dividing each by
# totaly no. of review, basically find and average. 

def document_vector(text):
    
    #remove out-of-vocabulary words or checking if review words lies in the vocabulary
    
    doc = [ word for word in text.split() if word in model.wv.index_to_key]
    
    return np.mean(model.wv[doc],axis=0) # Applying Average Word2Vec to calculate the Vector for entire Sentence

In [49]:
# Converting 1st review into vector

document_vector(df.review[0])

array([-0.16699265,  0.40380013,  0.12725222,  0.26538756, -0.16387628,
       -0.59095365,  0.21284302,  0.9179305 , -0.3510755 , -0.2612717 ,
       -0.29615664, -0.45356408,  0.09916428,  0.07938936,  0.15757693,
       -0.08020486,  0.03569493, -0.32331404, -0.07368887, -0.6343645 ,
        0.05235797,  0.25772098,  0.10620508, -0.2802313 , -0.34279436,
       -0.05181248, -0.32191357,  0.01180453, -0.34712377, -0.00675351,
        0.35538337, -0.00733319,  0.238105  , -0.29262114, -0.13847294,
        0.40626773,  0.09530991, -0.39276847, -0.24746914, -0.7502983 ,
        0.11375126, -0.2854766 ,  0.08595166, -0.0822853 ,  0.50667423,
       -0.19234785, -0.27283788, -0.01696321,  0.1424457 ,  0.37158856,
        0.14013223, -0.36089423, -0.43362316, -0.08737902, -0.12145112,
        0.20002301,  0.25506818,  0.02126458, -0.28768867,  0.10086247,
        0.08087148,  0.08816463,  0.03454203, -0.10112143, -0.4450149 ,
        0.2992604 ,  0.054784  ,  0.05580501, -0.33470225,  0.28

In [50]:
from tqdm import tqdm

x = []
for doc in tqdm(df.review):
    x.append(document_vector(doc))

100%|███████████████████████████████████████| 9983/9983 [12:22<00:00, 13.44it/s]


In [54]:
x = np.array(x)

In [55]:
x.shape # 9983 review with 100D

(9983, 100)

In [57]:
#Encoding the target variable using Label encoder

lb = LabelEncoder()
y = lb.fit_transform(df.sentiment)

In [58]:
#Splitting the data

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [65]:
#Random Forest
 
#Creating Model Object
rf = RandomForestClassifier()

#training the model
rf.fit(x_train,y_train)

#prediciton
y_pred4 = rf.predict(x_test)

#evaluation
accuracy_score(y_test, y_pred4)

0.7521281922884326